on:
 push:

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Before checkout
      run: ls -al 

    - name: clone repository
      uses: actions/checkout@v4

    - name: After checkout
      run: ls -al 

    - name: build
      run: echo "BUILD"
    
    - name: Dockerize
      run: echo "Dockerize"
    
    - name: Push to docker hub
      run: echo "Push to docker hub"
    
    - name: Connect to server
      run: echo "Connect to server"
    
    - name: Run container
      run: echo "Run container"