on:
 push:

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
    - name: clone
      run: echo "clone"
    
    - name: build
      run: echo "build"
    
    - name: Dockerize
      run: echo "Dockerize"
    
    - name: Push to docker hub
      run: echo "Push to docker hub"
    
    - name: Connect to server
      run: echo "Connect to server"
    
    - name: Run container
      run: echo "Run container"